language: c
sudo: false
branches:
  only: master
env:
  global:
  - GH_REF: github.com/rwos/gifstopmotion.git
  - secure: NUc8RJTj7XGnDaClxlpZP3XDWPqindTqugT/uADoabGtHp5zmNES1Yk4yHFM9YZOfrKzZ/sD3XmJy+syMnuYldd9fBa8FYevOOa4KnEcX45LrFIsxL2Thvf2nKvh8xVJDDkGpgng0/iwGjE6DZvjbkB5/JmPEJPJgIHdYGlBRh2wTCOOCu9ze6ya48Qn9M5tRIhO2ge/JkrEP8v/LUdgOkbaUT9S5CJxk+nPmCIRm25oBRz/I0TLoRUnX5trJ1280lKvWnlUGY/S1k4dgeTvuoqPUxKlR8vsS9qk9Y4uT8dTi9XiHQT0+oMdLVsT488y3GRW6K9/G5An3Mr0GyXJUtbC6ImX7EV8NnPWV9d3cYClVxX3qjprdjE49+6hIujE2FPczG5iWtb3xe/8Drro5nSh2BG6GyvyhB1MOYHPR2KYPdP4SFF5HZPpGGwaE/zVTsgXSi9qEhzT1KmTb67FfCH398B/GThuDFDY4xW6X5RzLoswKXUfzJXjlLPwjtQs584CoZZzi9zAXYBLoA9Tw5BRW/WrutMvtF4iTA2wrb8/3PIOKha6xrq7HBh1OnenqOj73y3B5Nf25bb43xkLjM/uTg57ZwfII15fvMchv5PSyAy0kHz3LfM7//Hi7OVQnZv4IF6eRupNVrmetRgdhFK7+EQmCgI914rT0RF2s/I=
before_install: 
install: 
before_script: 
script: make deploy
after_script: 
